dimensions:
  - &model_name "model_name"
  - &level "Level"
  - &device_id "device_id"

ts_metrics:
  counter:
    - name: CounterTsMetricExample
      unit: ms
      dimensions: [*model_name, *level]
  gauge:
    - name: GaugeTsMetricExample
      unit: ms
      dimensions: [*model_name, *level]
    - name: CPUUtilization
      unit: percent
      dimensions: [*level]
    - name: MemoryUsed
      unit: MB
      dimensions: [*level]
    - name: MemoryAvailable
      unit: MB
      dimensions: [*level]
    - name: MemoryUtilization
      unit: percent
      dimensions: [*level]
    - name: DiskUsage
      unit: GB
      dimensions: [*level]
    - name: DiskUtilization
      unit: percent
      dimensions: [*level]
    - name: DiskAvailable
      unit: GB
      dimensions: [*level]
    - name: GPUMemoryUtilization
      unit: percent
      dimensions: [*level, *device_id]
    - name: GPUMemoryUsed
      unit: MB
      dimensions: [*level, *device_id]
    - name: GPUUtilization
      unit: percent
      dimensions: [*level, *device_id]
  histogram:
    - name: HistogramTsMetricExample
      unit: ms
      dimensions: [*model_name, *level]

model_metrics:
  counter:
    - name: CounterModelMetricNameExample
      unit: ms
      dimensions: [*model_name, *level]
    - name: InferenceTimeInMS
      unit: ms
      dimensions: [*model_name, *level]
    - name: NumberOfMetrics
      unit: count
      dimensions: [*model_name, *level]
  gauge:
    - name: GaugeModelMetricNameExample
      unit: ms
      dimensions: [*model_name, *level]
  histogram:
    - name: HistogramModelMetricNameExample
      unit: ms
      dimensions: [*model_name, *level]
