dimensions:
  - &model_name "ModelName"
  - &level "Level"
  - &device_id "device_id"

ts_metrics:
  counter:
    - name: Requests2XX
      unit: count
      dimensions: [*level]
    - name: Requests4XX
      unit: count
      dimensions: [*level]
    - name: Requests5XX
      unit: count
      dimensions: [*level]
  gauge:
    - name: QueueTime
      unit: ms
      dimensions: [*level]
    - name: WorkerThreadTime
      unit: ms
      dimensions: [*level]
    - name: CPUUtilization
      unit: percent
      dimensions: [*level]
    - name: MemoryUsed
      unit: MB
      dimensions: [*level]
    - name: MemoryAvailable
      unit: MB
      dimensions: [*level]
    - name: MemoryUtilization
      unit: percent
      dimensions: [*level]
    - name: DiskUsage
      unit: GB
      dimensions: [*level]
    - name: DiskUtilization
      unit: percent
      dimensions: [*level]
    - name: DiskAvailable
      unit: GB
      dimensions: [*level]
    - name: GPUMemoryUtilization
      unit: percent
      dimensions: [*level, *device_id]
    - name: GPUMemoryUsed
      unit: MB
      dimensions: [*level, *device_id]
    - name: GPUUtilization
      unit: percent
      dimensions: [*level, *device_id]

model_metrics:
  gauge:
    - name: HandlerTime
      unit: ms
      dimensions: [*model_name, *level]
    - name: PredictionTime
      unit: ms
      dimensions: [*model_name, *level]
