minWorkers: 1
maxWorkers: 1
maxBatchDelay: 100
responseTimeout: 900
batchSize: 16

handler:
    model_name: meta-llama/Llama-2-13b-hf
    tp_degree: 6
    max_length: 100

micro_batching:
    micro_batch_size: 4
    parallelism:
        preprocess: 2
        inference: 1
        postprocess: 2
