minWorkers: 1
maxWorkers: 1
maxBatchDelay: 100
responseTimeout: 1200

handler:
    max_length: 50
    manual_seed: 40
    batch_size: 2
    tp_degree: 2
    amp: f16
    model_name: decapoda-research/llama-7b-hf
